name: Build all

on:
  check_suite:
    # once garnix has completed
    types: [completed]
  push:
    tags:
      - "*"

jobs:
  build-pi3-direct:
    uses: ./.github/workflows/build.yml
    with:
      host: pi3-direct
    permissions:
      contents: write
      id-token: write
  build-pi3-uboot:
    uses: ./.github/workflows/build.yml
    with:
      host: pi3-uboot
    permissions:
      contents: write
      id-token: write
  build-pi4-direct:
    uses: ./.github/workflows/build.yml
    with:
      host: pi4-direct
    permissions:
      contents: write
      id-token: write
  build-pi4-uboot:
    uses: ./.github/workflows/build.yml
    with:
      host: pi4-uboot
    permissions:
      contents: write
      id-token: write
  build-pi5-direct:
    uses: ./.github/workflows/build.yml
    with:
      host: pi5-direct
    permissions:
      contents: write
      id-token: write
  build-pi5-uboot:
    uses: ./.github/workflows/build.yml
    with:
      host: pi5-uboot
    permissions:
      contents: write
      id-token: write
