name: Build all

on:
  check_suite:
    # once garnix has completed
    types: [completed]
  push:
    tags:
      - "*"

jobs:
  build-pi3:
    uses: ./.github/workflows/build.yml
    with:
      host: pi3
    permissions:
      contents: write
      id-token: write
  build-pi4:
    uses: ./.github/workflows/build.yml
    with:
      host: pi4
    permissions:
      contents: write
      id-token: write
  # disabled until pi5 works, so the builds arent all red
  # build-pi5:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     host: pi5
  #   permissions:
  #     contents: write
  #     id-token: write
